/* ============================================
   Casa Verbena · Base de datos de propiedades
   Compartida entre index.html y propiedad.html
   ============================================ */

const PROPIEDADES = [
  {
    id: "casa-roldan",
    nombre: "Casa Roldán",
    barrio: "Palermo Chico",
    tipo: "Casa",
    operacion: "Comprar",
    precio: 685000,
    precioTexto: "USD 685.000",
    resumen: "4 amb · 280 m² · jardín y pileta",
    img: "https://http2.mlstatic.com/D_NQ_NP_809183-MLA109108856536_042026-OO.webp",
    direccion: "Calle Roldán 2480, Palermo Chico, CABA",
    lat: -34.5772,
    lng: -58.4098,
    superficie: "280 m² cubiertos + 140 m² de jardín",
    caracteristicas: [
      "4 dormitorios, 2 de ellos en suite",
      "Pileta climatizada con deck de madera",
      "Jardín con parrilla y quincho",
      "Cochera cubierta para 2 autos",
      "Living comedor con doble altura",
      "Cocina con isla y office independiente",
      "Calefacción por losa radiante",
      "Alarma y monitoreo 24 horas",
    ],
    requisitos: [
      "Reserva del 5% para retirar la propiedad del mercado",
      "Seña del 30% al firmar el boleto de compraventa",
      "Saldo restante el día de la escritura ante escribano",
      "Estudio de títulos y verificación de dominio incluidos",
    ],
  },
  {
    id: "alvear-7b",
    nombre: "Alvear 1234, 7°B",
    barrio: "Recoleta",
    tipo: "Departamento",
    operacion: "Alquilar",
    precio: 1500,
    precioTexto: "USD 1.500 / mes",
    resumen: "5 ambientes · 110 m² · balcón francés",
    img: "https://http2.mlstatic.com/D_NQ_NP_673464-MLA110978936370_052026-OO.webp",
    direccion: "Av. Alvear 1234, piso 7°B, Recoleta, CABA",
    lat: -34.5882,
    lng: -58.3917,
    superficie: "110 m² · piso alto con vista despejada",
    caracteristicas: [
      "2 dormitorios + escritorio",
      "Balcón francés a la avenida",
      "Pisos de roble de Eslavonia originales",
      "Cocina equipada con electrodomésticos",
      "Portería permanente y ascensor de servicio",
      "Calefacción central por radiadores",
      "Baulera en el subsuelo incluida",
    ],
    requisitos: [
      "Garantía propietaria en CABA o seguro de caución",
      "Recibos de sueldo que tripliquen el valor del alquiler",
      "Depósito equivalente a un mes de alquiler",
      "Contrato a 36 meses según ley vigente",
    ],
  },
  {
    id: "loft-defensa",
    nombre: "Loft Defensa",
    barrio: "San Telmo",
    tipo: "Local",
    operacion: "Alquilar",
    precio: 3950,
    precioTexto: "USD 3.950 / mes",
    resumen: "Monoambiente · 436 m² · doble altura",
    img: "https://http2.mlstatic.com/D_NQ_NP_2X_673871-MLA110748766974_052026-F.webp",
    direccion: "Defensa 980, San Telmo, CABA",
    lat: -34.6195,
    lng: -58.3717,
    superficie: "436 m² · monoambiente con doble altura",
    caracteristicas: [
      "Espacio integrado tipo loft industrial",
      "Entrepiso de hierro y madera",
      "Ventanal de 4 metros al frente",
      "Cocina abierta con barra de hormigón",
      "Paredes de ladrillo a la vista restauradas",
      "Edificio reciclado de principios de 1900",
    ],
    requisitos: [
      "Garantía propietaria o seguro de caución",
      "Recibos de sueldo o monotributo categoría C o superior",
      "Depósito equivalente a un mes de alquiler",
      "Apto profesional con uso comercial limitado",
    ],
  },
  {
    id: "villa-sucre",
    nombre: "Villa Sucre",
    barrio: "Belgrano R",
    tipo: "Casa",
    operacion: "Comprar",
    precio: 850000,
    precioTexto: "USD 850.000",
    resumen: "9 amb · 420 m² · cochera doble",
    img: "https://http2.mlstatic.com/D_NQ_NP_822044-MLA107108420924_022026-OO.webp",
    direccion: "Conde 1700, Belgrano R, CABA",
    lat: -34.5618,
    lng: -58.4565,
    superficie: "420 m² cubiertos en lote de 600 m²",
    caracteristicas: [
      "5 dormitorios y dependencia de servicio",
      "Estilo inglés con detalles originales",
      "Jardín de invierno vidriado",
      "Biblioteca con boiserie de roble",
      "Cochera doble con portón automático",
      "Sótano acondicionado como bodega",
      "Sistema de riego y luces de jardín",
    ],
    requisitos: [
      "Reserva del 5% para retirar la propiedad del mercado",
      "Seña del 30% al firmar el boleto de compraventa",
      "Saldo restante el día de la escritura ante escribano",
      "Posibilidad de financiación parcial a evaluar",
    ],
  },
  {
    id: "ph-acevedo",
    nombre: "PH Acevedo",
    barrio: "Villa Crespo",
    tipo: "PH",
    operacion: "Comprar",
    precio: 175000,
    precioTexto: "USD 175.000",
    resumen: "5 amb · 260 m² · terraza propia",
    img: "https://http2.mlstatic.com/D_NQ_NP_829113-MLA110965054934_052026-OO.webp0",
    direccion: "Acevedo 650, Villa Crespo, CABA",
    lat: -34.5985,
    lng: -58.4395,
    superficie: "230 m² + 30 m² de terraza exclusiva",
    caracteristicas: [
      "1 dormitorio amplio + estudio",
      "Terraza propia con conexión para parrilla",
      "Sin expensas, entrada independiente",
      "Pisos calcáreos originales restaurados",
      "Cocina nueva con muebles a medida",
      "Patio interno con cantero verde",
    ],
    requisitos: [
      "Reserva del 5% para retirar la propiedad del mercado",
      "Seña del 30% al firmar el boleto de compraventa",
      "Saldo restante el día de la escritura ante escribano",
      "Reglamento de copropiedad disponible para revisión",
    ],
  },
  {
    id: "casa-del-roble",
    nombre: "Casa del Roble",
    barrio: "San Isidro",
    tipo: "Casa",
    operacion: "Comprar",
    precio: 890000,
    precioTexto: "USD 890.000",
    resumen: "4 amb · 866 m² · parque arbolado",
    img: "https://http2.mlstatic.com/D_NQ_NP_685511-MLA111864104635_052026-OO.webp",
    direccion: "Roque Sáenz Peña 1450, San Isidro, Buenos Aires",
    lat: -34.4736,
    lng: -58.5275,
    superficie: "866 m² cubiertos en lote de 800 m²",
    caracteristicas: [
      "4 dormitorios + playroom",
      "Parque añoso con roble centenario",
      "Galería con piso de piedra Mar del Plata",
      "Pileta con solárium",
      "Cochera para 3 autos",
      "Casa de huéspedes independiente",
      "A 8 cuadras de la estación de tren",
    ],
    requisitos: [
      "Reserva del 5% para retirar la propiedad del mercado",
      "Seña del 30% al firmar el boleto de compraventa",
      "Saldo restante el día de la escritura ante escribano",
      "Mensura y plano de obra al día incluidos",
    ],
  },
  {
    id: "local-gurruchaga",
    nombre: "Local Gurruchaga",
    barrio: "Palermo Soho",
    tipo: "Local",
    operacion: "Alquilar",
    precio: 2400,
    precioTexto: "USD 2.400 / mes",
    resumen: "Local a la calle · 95 m² · gran vidriera",
    img: "https://http2.mlstatic.com/D_NQ_NP_2X_668951-MLA101072879125_122025-F.webp",
    direccion: "Gurruchaga 1820, Palermo Soho, CABA",
    lat: -34.5882,
    lng: -58.4290,
    superficie: "95 m² en planta baja + 20 m² de entrepiso",
    caracteristicas: [
      "Vidriera de 6 metros sobre calle comercial",
      "Entrepiso para depósito u oficina",
      "Baño completo y kitchenette",
      "Instalación eléctrica trifásica",
      "Cortina metálica con motor",
      "Alta circulación peatonal",
    ],
    requisitos: [
      "Garantía propietaria o seguro de caución comercial",
      "Habilitación a cargo del locatario",
      "Depósito equivalente a dos meses de alquiler",
      "Contrato comercial a convenir, mínimo 36 meses",
    ],
  },
  {
    id: "oficina-catalinas",
    nombre: "Oficina Catalinas",
    barrio: "Retiro",
    tipo: "Oficina",
    operacion: "Comprar",
    precio: 410000,
    precioTexto: "USD 410.000",
    resumen: "Oficina premium · 130 m² · vista al río",
    img: "https://http2.mlstatic.com/D_NQ_NP_2X_917675-MLA110380768871_042026-F.webp",
    direccion: "Av. Eduardo Madero 900, Catalinas, Retiro, CABA",
    lat: -34.5925,
    lng: -58.3740,
    superficie: "130 m² en piso alto de torre corporativa",
    caracteristicas: [
      "Planta libre con vista abierta al Río de la Plata",
      "Piso técnico y cielorraso desmontable",
      "Aire acondicionado central VRV",
      "2 cocheras en subsuelo incluidas",
      "Seguridad y recepción del edificio 24 hs",
      "Acceso directo a transporte y autopista",
    ],
    requisitos: [
      "Reserva del 5% para retirar la propiedad del mercado",
      "Seña del 30% al firmar el boleto de compraventa",
      "Saldo restante el día de la escritura ante escribano",
      "Expensas y certificado de dominio al día",
    ],
  },
];

/* Helper para buscar una propiedad por su id */
function getPropiedad(id) {
  return PROPIEDADES.find((p) => p.id === id) || null;
}
